# Generated by Django 3.2.8 on 2022-01-21 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, unique=True, verbose_name='商品グループ')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='発売日')),
                ('description', models.CharField(max_length=10000, verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsgroup', verbose_name='商品グループ')),
            ],
        ),
    ]
